### PR TITLE
Change logging output from print to logging module

### PR DESCRIPTION
**Pull request by cooperlees**
- Moves output to stderr vs. stdout
- Timestamps, line numbers added to output
- Adds log levels to output

This should also allow output to be seen by SystemD's journal (journalctl) ...

### CODE REVIEW

**Comment by cooperlees** [comment]
Even changing the output to stderr, (I installed this PPR branch) I don't get the output in systemd :| - even setting `Type=simple` ... What am I missing here?

**Comment by ibizaman** [comment]
I’ll try to check what’s up with systemd. I can already merge this PR though. Do you want me to merge it or do you want to leave it open until we figure out systemd output?

Thanks for the PR!

**Comment by cooperlees** [comment]
Feel free to merge - I’d prefer the output anyways - I’ll have another debug to try workout why no systemd output one evening soon.

**Comment by ibizaman** [comment]
Awesome, merged! Thank you for the PR!

**Pull request merged**
