### PR TITLE
Format files with black

### PR DESCRIPTION
**Pull request by cooperlees**
- Format all .py files with black - https://github.com/psf/black
- Add GitHub Actions CI to ensure we don't forget

### CODE REVIEW

**Comment by cooperlees** [comment]
Hmm - no idea why CI didn't run - Do you need to approve it to run?

**Comment by ibizaman** [comment]
That’s a good question. I’m not an expert but I don’t see any obvious mistake.

**Review by ibizaman — APPROVED** [review]

**Comment by ibizaman** [comment]
I merged it to see if that was the issue.

EDIT: that was it but it’s weird. I think we’re missing something.

**Comment by cooperlees** [comment]
https://github.com/ibizaman/godaddyip/actions/runs/1260436399 ran ... So lets see on future PRs.

**Pull request merged**
