### PR TITLE
Add Support for updating AAAA record

### LINKED ISSUE #5: Add AAAA Support
Would you accept a PR to add AAAA (IPv6) record support?

### PR DESCRIPTION
**Pull request by cooperlees**
- Add support for a aaaarecord config param
  - Could be the same as arecord to dual stack or not
- Added second call to `update_arecord` + `get_current_ip` to update AAAA record too
  - Added new `record_type` param for better logging and use of correct config param
  - Use it as the tmp filename checking for IP changes
  - Didn't bother to run in parallel as we don't need this to be "fast"
- Moved to using a HTTPS endpoint that is dual stacked
  - api.ipify.org only has A Records and is IPv4 only ...
  - i.e. moved endpoint URL from "api.ipify.org" to "icanhazip.com"
- Had to use pycurl as I could not get a requests to prefer IPv4 on a dual stacked host
  - I tried multiple ways but gave up and lived with adding an extra dependency
  - Added requirement to requirements.txt + setup.py

Known limitations:
- cnames only cname the A Record (not AAAA) unless you dualstack
  - I dual stack ...
- I couldn't get config.get("aaaarecord") to work natively ... so hacked using config._config.get(...) ...
  - Please comment if you see the bug there

As always, formatted with black
- `/tmp/tg/bin/black godaddyip/__main__.py`

Test:
- Ran on my home router manually making my own venv
  - `python3 -m venv --upgrade-deps /tmp/tg`
  - `/tmp/tg/bin/pip install -r requests.txt`
  - `/tmp/tg/bin/python godaddyip/__main__.py run --config_files=/etc/godaddyip.yml --tmp_folder /tmp/cooper_godaddyip`

```
[2024-05-06 04:29:31,149] INFO: Updating A record home. (__main__.py:217)
[2024-05-06 04:29:31,150] INFO: Same IP 47.33.51.91 as previous one, nothing to do. (__main__.py:220)
[2024-05-06 04:29:31,234] INFO: Updating AAAA record home. (__main__.py:217)
[2024-05-06 04:29:31,681] INFO: Updating CNAME record tahoe. (__main__.py:236)
[2024-05-06 04:29:31,681] INFO: Same alias as previous one, nothing to do. (__main__.py:239)
[2024-05-06 04:29:31,681] INFO: Updating CNAME record home1. (__main__.py:236)
[2024-05-06 04:29:31,681] INFO: Same alias as previous one, nothing to do. (__main__.py:239)
[2024-05-06 04:29:31,681] INFO: Sleeping for 5 minutes. (__main__.py:185)
```

Fixes #5

### CODE REVIEW

**Comment by cooperlees** [comment]
Anything I need to do here? Any feedback? I see requests update got a merge. :)

**Review by ibizaman — APPROVED** [review]
Looks good! Thank you for the PR. If you don't mind fixing the merge conflicts, I'll merge the PR.

**Comment by ibizaman** [comment]
Ah well... I wanted to try GitHub's merge resolve conflict and managed to botch the `requirements.txt` file. Sorry /o\

**Comment by cooperlees** [comment]
Weird it couldn't handle that merge ... but I fixed it.

I might write some small actual unittests after this is merged too.

**Pull request merged**
